import { useQuery } from "../context/QueryContext";

export default function CheckboxCourse() {
  const {
    allCourseInProduct,
    selectedProduct,
    selectedCourse,
    handleSelectCourse,
  } = useQuery();
  // console.log(selectedProduct);

  return (
    <div style={{ height: "70dvh", overflow: "scroll" }}>
      {selectedProduct?.AssignmentID !== null ? (
        allCourseInProduct.map((course) => (
          <div key={course.CohortID}>
            <input
              id={course.CohortID}
              name={course.CohortID}
              type="checkbox"
              checked={selectedCourse?.includes(course.CohortID)}
              onChange={handleSelectCourse}
            />
            <label htmlFor={course.CohortID}>
              {course.CohortName.startsWith("Autogenerated")
                ? "Unassigned"
                : course.CohortName}{" "}
              ({course.StudentCount})
            </label>
          </div>
        ))
      ) : (
        <p>No course available</p>
      )}
    </div>
  );
}
